### ISSUE TITLE
ERR: The specified service does not exist as an installed service

### ISSUE THREAD

**Issue by publik2023** [sileshn/LinuxmintWSL#2]
### Requirements

- [ ] Yes
- [X] No

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Version

Microsoft Windows [Version 10.0.19045.2486]

### Kernel Version

Kernel version: 5.15.90.1

### Repro Steps

Hi 

I am getting this error when I double clic on mint.exe :  

Using: D:\LINUXMINT WSL2\LinuxmintlmdeWSL2\rootfs.tar.gz
Installing...
ERR: The specified service does not exist as an installed service.
HRESULT: 0x80070424
Press enter to exit...

thanks in advance for your help 

### Expected Behavior

Run Mint.exe to extract rootfs and register to WSL

### Actual Behavior

ERR: The specified service does not exist as an installed service.
HRESULT: 0x80070424
Press enter to exit...

**Comment by sileshn** [comment]
You have not installed the kernel

**Comment by publik2023** [comment]
Hi and thanks for your answer  : you right about it , I didn't see the update in the requirements list ,  but even after I installed it ,the issue is still the same ( I even rebooted the computer , wasn't sure if necessary )

here are the informations I got from wsl --version  

WSL version: 1.2.5.0
Kernel version: 5.15.90.1
WSLg version: 1.0.51
MSRDC version: 1.2.3770
Direct3D version: 1.608.2-61064218
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.19045.2486

**Comment by publik2023** [comment]
I want to add an information : I tried to install kali , ubunbu and even slackware with wsl and no issues at all

**Comment by sileshn** [comment]
Cannot reproduce the issue. 

![Screenshot 2023-05-01 011755](https://user-images.githubusercontent.com/977360/235373333-ce3e835f-fafa-463a-9a2b-d391eee66683.png)

**Comment by publik2023** [comment]
Hi  and thanks again for your help ,  to solve the problem , I copied something I found on the slacware wsl github and use this command instead using mint.exe 
wsl.exe --import mint d:\mint_wsl .\rootfs.tar.gz

**Comment by sileshn** [comment]
Whatever works for you..
