### ISSUE TITLE
Error: Can't open display:

### ISSUE THREAD

**Issue by Areshkew** [sileshn/LinuxmintWSL#3]
### Requirements

- [X] Yes
- [ ] No

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Version

Microsoft Windows [Version 10.0.22621.1555]

### Repro Steps

execute Gui APPS

### Expected Behavior

Open the App

### Actual Behavior

Error: Can't open display:

**Comment by sileshn** [comment]
I can't reproduce your issue. You'll have to look into your setup. 

![Screenshot 2023-05-01 011527](https://user-images.githubusercontent.com/977360/235373256-788739db-efb3-4bec-80d5-50031b9be7dc.png)

**Comment by Areshkew** [comment]
I fixed it, I had a configuration that disabled WSLg for using Xvnc.

I just deleted that file ".wslconfig" in c:/users.

Thank u for your time.
