### ISSUE TITLE
graphics broken

### ISSUE THREAD

**Issue by pro9code** [sileshn/LinuxmintWSL#9]
### Requirements

- [X] Yes
- [ ] No

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Version

Microsoft Windows [Version 10.0.22631.2861]

### Repro Steps

gedit
![image](https://github.com/sileshn/LinuxmintWSL2/assets/125939648/303e05f3-e512-487d-8306-335223f6d120)

### Expected Behavior

not that

### Actual Behavior

completely broken graphics

**Comment by pro9code** [comment]
also, how to open the gui?

**Comment by sileshn** [comment]
This is a barebone install. Not meant to be run with GUI. If you need graphics support, install the required packages.

**Comment by pro9code** [comment]
and what are those?

**Comment by sileshn** [comment]
Depends on which desktop environment you need. Google is your friend.

If you are referring to wslg display issues, add wsl2.packagedGpuLibs=false to your .wslconfig file. It seems to be triggered after the latest windows update.

(or)

Update your graphics drivers to the latest if you are running the windows installed ones.

One of the many issues discussed on wslg's  github.
https://github.com/microsoft/wslg/issues/1144

**Comment by RobertBernstein** [comment]
`gedit` worked fine for me after executing: `sudo apt install cinnamon-desktop-environment`
